import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <div class="shell">
      <nav class="topbar">
        <span class="brand">Smart&nbsp;Inbox</span>
        <span class="tag">pharmacovigilance first-pass triage</span>
        <span class="spacer"></span>
        <span class="synthetic" title="Every document in this system is generated by testdata/generator. No real patient data is used anywhere.">
          synthetic data only
        </span>
      </nav>
      <router-outlet />
    </div>
  `,
  styles: [`
    .shell { min-height: 100vh; }
    .topbar {
      display: flex; align-items: baseline; gap: 12px;
      padding: 10px 20px; background: #1f3b54; color: #fff;
    }
    .brand { font-weight: 700; font-size: 16px; letter-spacing: .3px; }
    .tag { font-size: 12px; color: #b9cbdb; }
    .spacer { flex: 1; }
    .synthetic {
      font-size: 11px; background: #2d5573; padding: 3px 9px; border-radius: 10px;
      color: #cfe0ee; cursor: help;
    }
  `],
})
export class App {}
