-- =====================================================================================
-- Smart Inbox — V1: tables
--
-- PROJECT_PLAN §9.1–9.3. Eighteen application tables plus two for the literature bonus.
--
-- Two conventions run through the whole schema and both exist for a regulatory reason:
--
--   * APPEND-ONLY.  Nothing a reviewer touches is ever updated in place. CLASSIFICATION and
--     EXTRACTED_FIELD carry a SUPERSEDED_BY self-reference: an override inserts a new row and
--     points the old one at it. The AI's original answer therefore survives forever, which is
--     what a 21 CFR Part 11-style system requires (E40).
--
--   * EVIDENCE IS A ROW, NOT A STRING.  Every extracted fact hangs FIELD_EVIDENCE rows that
--     carry the quote, its character offsets, a bounding box and — crucially — a VERIFIED flag
--     written by code that proved the quote exists in the source. The model's own citation is
--     never trusted (E27).
--
-- Y/N flags are CHAR(1) with a CHECK rather than a boolean, so the schema reads identically
-- from SQL*Plus, JDBC and the Flyway history on every supported Oracle version.
-- =====================================================================================


-- -------------------------------------------------------------------------------------
-- 1. INBOX_MESSAGE — one row per email pulled from the mailbox.
-- -------------------------------------------------------------------------------------
CREATE TABLE inbox_message (
  id              NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- E2: idempotent polling. Message-ID header when present, else a SHA-256 of
  -- (from, subject, sent_at, normalised body). The unique constraint makes re-processing
  -- impossible by construction rather than by convention.
  dedupe_key      VARCHAR2(200) NOT NULL,
  message_id_hdr  VARCHAR2(500),
  folder          VARCHAR2(200) DEFAULT 'INBOX' NOT NULL,
  imap_uid        NUMBER(19),
  sender_email    VARCHAR2(320),
  sender_name     VARCHAR2(320),
  recipient_email VARCHAR2(320),
  subject         VARCHAR2(1000),
  sent_at         TIMESTAMP(6) WITH TIME ZONE,
  received_at     TIMESTAMP(6) WITH TIME ZONE,
  body_text       CLOB,
  body_html       CLOB,
  body_charset    VARCHAR2(60),
  -- E10: character offset in body_text at which the quoted reply/forward history begins.
  -- NULL means no quoted section was detected. New text before this offset is the primary
  -- source; quoted text after it is retained but never counted as an independent report.
  quoted_offset   NUMBER(10),
  status          VARCHAR2(30)  DEFAULT 'RECEIVED' NOT NULL,
  needs_attention CHAR(1)       DEFAULT 'N' NOT NULL,
  attention_reason VARCHAR2(500),
  created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_inbox_message_dedupe UNIQUE (dedupe_key),
  CONSTRAINT ck_inbox_message_status CHECK (status IN (
    'RECEIVED','PARSING','PARSED','CLASSIFYING','CLASSIFIED','EXTRACTING',
    'READY_FOR_REVIEW','REVIEWED','NEEDS_ATTENTION','FAILED')),
  CONSTRAINT ck_inbox_message_attn CHECK (needs_attention IN ('Y','N'))
);

COMMENT ON TABLE inbox_message IS 'One email pulled over IMAP. dedupe_key is the E2 idempotency key.';


-- -------------------------------------------------------------------------------------
-- 2. MESSAGE_ATTACHMENT — every part we found, including the ones we deliberately skip.
-- -------------------------------------------------------------------------------------
CREATE TABLE message_attachment (
  id             NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id     NUMBER(19)    NOT NULL,
  filename       VARCHAR2(500),
  -- E4: the declared type and the sniffed type are stored separately on purpose. They
  -- disagreeing (a PDF sent as application/octet-stream) is itself audit-interesting.
  declared_type  VARCHAR2(200),
  sniffed_type   VARCHAR2(200),
  size_bytes     NUMBER(19)    DEFAULT 0 NOT NULL,
  sha256         VARCHAR2(64),
  blob_path      VARCHAR2(1000),
  -- E5: 0 = attached directly, 1 = hoisted out of a message/rfc822 forward.
  nesting_level  NUMBER(3)     DEFAULT 0 NOT NULL,
  processed      CHAR(1)       DEFAULT 'N' NOT NULL,
  -- E6: non-PDF types are logged with a reason rather than silently dropped.
  skip_reason    VARCHAR2(200),
  created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_attachment_message FOREIGN KEY (message_id)
    REFERENCES inbox_message (id) ON DELETE CASCADE,
  CONSTRAINT ck_attachment_processed CHECK (processed IN ('Y','N')),
  CONSTRAINT ck_attachment_skip CHECK (skip_reason IS NULL OR skip_reason IN (
    'UNSUPPORTED_TYPE','TOO_LARGE','ENCRYPTED','CORRUPT','EMPTY',
    'DUPLICATE_CONTENT','NESTING_TOO_DEEP'))
);


-- -------------------------------------------------------------------------------------
-- 3. DOCUMENT — the unit of understanding. An email body is a document too (E11), so
--    bodies and PDFs share one parse path, one evidence model and one review UI.
-- -------------------------------------------------------------------------------------
CREATE TABLE document (
  id               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id       NUMBER(19),                 -- NULL for a literature upload
  attachment_id    NUMBER(19),                 -- NULL for an email body
  source_kind      VARCHAR2(30) NOT NULL,
  filename         VARCHAR2(500),
  -- E9: content address. Parse results are cached against this, so the same PDF attached to
  -- two emails costs zero additional LLM calls.
  content_sha256   VARCHAR2(64),
  blob_path        VARCHAR2(1000),
  page_count       NUMBER(6)    DEFAULT 0 NOT NULL,
  -- E12: flavour is detected per page; these are roll-ups and MIXED is a legal value.
  doc_rendering    VARCHAR2(20),
  doc_genre        VARCHAR2(20),
  primary_language VARCHAR2(20),
  is_encrypted     CHAR(1)      DEFAULT 'N' NOT NULL,   -- E7
  truncated        CHAR(1)      DEFAULT 'N' NOT NULL,   -- E8
  parse_status     VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  parse_error      VARCHAR2(2000),
  parse_ms         NUMBER(10),
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_document_message FOREIGN KEY (message_id)
    REFERENCES inbox_message (id) ON DELETE CASCADE,
  CONSTRAINT fk_document_attachment FOREIGN KEY (attachment_id)
    REFERENCES message_attachment (id) ON DELETE CASCADE,
  CONSTRAINT ck_document_kind CHECK (source_kind IN
    ('EMAIL_BODY','PDF_ATTACHMENT','IMAGE_ATTACHMENT','UPLOADED_ARTICLE')),
  CONSTRAINT ck_document_rendering CHECK (doc_rendering IS NULL OR doc_rendering IN
    ('DIGITAL','SCANNED','MIXED')),
  CONSTRAINT ck_document_genre CHECK (doc_genre IS NULL OR doc_genre IN
    ('FORM','ARTICLE','LETTER','MIXED')),
  CONSTRAINT ck_document_encrypted CHECK (is_encrypted IN ('Y','N')),
  CONSTRAINT ck_document_truncated CHECK (truncated IN ('Y','N')),
  -- PARSED and PARSE_FAILED are the two terminal states the E39 completion barrier waits for.
  CONSTRAINT ck_document_parse_status CHECK (parse_status IN
    ('PENDING','PARSING','PARSED','PARSE_FAILED'))
);

COMMENT ON TABLE document IS 'A parseable unit: an email body (E11), a PDF attachment, or an uploaded article.';


-- -------------------------------------------------------------------------------------
-- 4. DOCUMENT_PAGE — per-page flavour, text and the rendered image behind the UI overlay.
-- -------------------------------------------------------------------------------------
CREATE TABLE document_page (
  id              NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id     NUMBER(19)   NOT NULL,
  page_no         NUMBER(6)    NOT NULL,
  rendering       VARCHAR2(20),
  genre           VARCHAR2(20),
  language        VARCHAR2(20),
  lang_confidence NUMBER(5,4),
  char_count      NUMBER(10)   DEFAULT 0 NOT NULL,
  has_text_layer  CHAR(1)      DEFAULT 'N' NOT NULL,
  column_count    NUMBER(3)    DEFAULT 1 NOT NULL,     -- E14
  -- E16: the ORIGINAL is canonical. Every evidence quote and every character offset points
  -- here, never at the translation, because the original is the record of truth for audit.
  text_original   CLOB,
  text_english    CLOB,
  -- E34: vision transcription legibility, 0..1. Caps the confidence of every field sourced
  -- from this page, so handwriting uncertainty flows downstream instead of stopping at OCR.
  legibility      NUMBER(5,4)  DEFAULT 1 NOT NULL,
  width           NUMBER(10,2),
  height          NUMBER(10,2),
  rotation        NUMBER(6)    DEFAULT 0 NOT NULL,
  render_path     VARCHAR2(1000),
  -- Character-offset -> bounding-box index built at parse time (§10.3). This is what makes
  -- click-to-highlight possible without embedding a PDF renderer in the browser.
  span_index_json CLOB,
  CONSTRAINT fk_page_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT uq_page_document_no UNIQUE (document_id, page_no),
  CONSTRAINT ck_page_rendering CHECK (rendering IS NULL OR rendering IN ('DIGITAL','SCANNED')),
  CONSTRAINT ck_page_genre CHECK (genre IS NULL OR genre IN ('FORM','ARTICLE','LETTER')),
  CONSTRAINT ck_page_text_layer CHECK (has_text_layer IN ('Y','N')),
  CONSTRAINT ck_page_legibility CHECK (legibility BETWEEN 0 AND 1)
);


-- -------------------------------------------------------------------------------------
-- 5. DOCUMENT_SECTION — heading segmentation, and the E15 exclusion that stops the model
--    manufacturing a "patient" out of a bibliography entry.
-- -------------------------------------------------------------------------------------
CREATE TABLE document_section (
  id                NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       NUMBER(19)   NOT NULL,
  page_no           NUMBER(6)    NOT NULL,
  section_index     NUMBER(6)    DEFAULT 0 NOT NULL,
  heading           VARCHAR2(500),
  section_kind      VARCHAR2(40),
  char_start        NUMBER(10),
  char_end          NUMBER(10),
  -- E15: References / Acknowledgements / Conflict of interest / Funding are withheld from the
  -- extraction prompt but still feed the summary prompt.
  excluded_from_case CHAR(1)     DEFAULT 'N' NOT NULL,
  CONSTRAINT fk_section_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_section_excluded CHECK (excluded_from_case IN ('Y','N')),
  CONSTRAINT ck_section_kind CHECK (section_kind IS NULL OR section_kind IN (
    'TITLE','ABSTRACT','INTRODUCTION','METHODS','CASE_REPORT','RESULTS','DISCUSSION',
    'CONCLUSION','REFERENCES','ACKNOWLEDGEMENTS','CONFLICT_OF_INTEREST','FUNDING',
    'FORM_FIELDS','LETTER_BODY','OTHER'))
);


-- -------------------------------------------------------------------------------------
-- 6. DOCUMENT_TABLE — tables stay tables (R5). Headers and rows are stored as JSON arrays,
--    never flattened into a string.
-- -------------------------------------------------------------------------------------
CREATE TABLE document_table (
  id                NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id       NUMBER(19)   NOT NULL,
  page_no           NUMBER(6)    NOT NULL,
  table_index       NUMBER(6)    DEFAULT 0 NOT NULL,
  n_rows            NUMBER(6)    DEFAULT 0 NOT NULL,
  n_cols            NUMBER(6)    DEFAULT 0 NOT NULL,
  caption           VARCHAR2(1000),
  headers_json      CLOB,
  rows_json         CLOB,
  bbox              VARCHAR2(120),
  -- E18: 'PYMUPDF' is the primary path; 'VISION' is the fallback for borderless grids;
  -- 'MERGED' marks a table stitched across a page break.
  extraction_method VARCHAR2(20) DEFAULT 'PYMUPDF' NOT NULL,
  continued_from_id NUMBER(19),
  CONSTRAINT fk_table_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_table_method CHECK (extraction_method IN ('PYMUPDF','VISION','MERGED'))
);


-- -------------------------------------------------------------------------------------
-- 7. DOCUMENT_IMAGE — only *meaningful* images survive the E19 filter and reach this table.
--    needs_review is always 'Y': the brief requires a human to check image interpretation.
-- -------------------------------------------------------------------------------------
CREATE TABLE document_image (
  id              NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id     NUMBER(19)   NOT NULL,
  page_no         NUMBER(6)    NOT NULL,
  image_index     NUMBER(6)    DEFAULT 0 NOT NULL,
  xref            NUMBER(10),
  bbox            VARCHAR2(120),
  width           NUMBER(10),
  height          NUMBER(10),
  area_ratio      NUMBER(7,6),
  category        VARCHAR2(30),
  description     VARCHAR2(4000),
  mentions_defect CHAR(1)      DEFAULT 'N' NOT NULL,
  mentions_injury CHAR(1)      DEFAULT 'N' NOT NULL,
  confidence      NUMBER(5,4),
  needs_review    CHAR(1)      DEFAULT 'Y' NOT NULL,
  blob_path       VARCHAR2(1000),
  ai_call_id      NUMBER(19),
  CONSTRAINT fk_image_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_image_category CHECK (category IS NULL OR category IN
    ('PRODUCT_DEFECT','CLINICAL_PHOTO','FORM_CHECKBOX','CHART','OTHER')),
  CONSTRAINT ck_image_defect CHECK (mentions_defect IN ('Y','N')),
  CONSTRAINT ck_image_injury CHECK (mentions_injury IN ('Y','N')),
  CONSTRAINT ck_image_review CHECK (needs_review IN ('Y','N'))
);


-- -------------------------------------------------------------------------------------
-- 8. DOCUMENT_SUMMARY — R7: the 10–15 sentence summary plus a relevance verdict and reason.
-- -------------------------------------------------------------------------------------
CREATE TABLE document_summary (
  id               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id      NUMBER(19)   NOT NULL,
  summary_text     CLOB,
  sentence_count   NUMBER(6)    DEFAULT 0 NOT NULL,
  relevance        VARCHAR2(20),
  relevance_reason VARCHAR2(2000),
  model            VARCHAR2(100),
  prompt_version   VARCHAR2(40),
  ai_call_id       NUMBER(19),
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_summary_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_summary_relevance CHECK (relevance IS NULL OR relevance IN
    ('RELEVANT','POSSIBLY','NOT_RELEVANT'))
);


-- -------------------------------------------------------------------------------------
-- 9. CLASSIFICATION — multi-label, one row per label (E23/E24: labels are independent
--    booleans, never a softmax). Classified at both levels (E25): each document, and the
--    message as the union.
-- -------------------------------------------------------------------------------------
CREATE TABLE classification (
  id             NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type   VARCHAR2(20) NOT NULL,
  subject_id     NUMBER(19)   NOT NULL,
  category       VARCHAR2(30) NOT NULL,
  confidence     NUMBER(5,4)  DEFAULT 0 NOT NULL,
  reason         VARCHAR2(2000),
  -- The unit that triggered this label when rolled up to message level (E25).
  triggered_by_document_id NUMBER(19),
  decided_by     VARCHAR2(20) DEFAULT 'AI' NOT NULL,
  decided_by_user VARCHAR2(200),
  -- E40: an override never updates this row; it inserts a new one and points here.
  superseded_by  NUMBER(19),
  model          VARCHAR2(100),
  prompt_version VARCHAR2(40),
  ai_call_id     NUMBER(19),
  created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_classification_subject CHECK (subject_type IN ('MESSAGE','DOCUMENT')),
  CONSTRAINT ck_classification_category CHECK (category IN
    ('ICSR','ICSR_INCOMPLETE','PQC','MI','NOT_RELEVANT')),
  CONSTRAINT ck_classification_decided CHECK (decided_by IN ('AI','REVIEWER','RULE')),
  CONSTRAINT ck_classification_conf CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT fk_classification_superseded FOREIGN KEY (superseded_by)
    REFERENCES classification (id)
);


-- -------------------------------------------------------------------------------------
-- 10. ICSR_VALIDITY — E22. The model reports the four minimum criteria as an explicit
--     checklist; the ICSR label itself is then decided by RULE, not by the model.
-- -------------------------------------------------------------------------------------
CREATE TABLE icsr_validity (
  id                    NUMBER(19)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification_id     NUMBER(19)  NOT NULL,
  has_patient           CHAR(1)     DEFAULT 'N' NOT NULL,
  patient_confidence    NUMBER(5,4) DEFAULT 0 NOT NULL,
  patient_evidence      VARCHAR2(2000),
  has_reporter          CHAR(1)     DEFAULT 'N' NOT NULL,
  reporter_confidence   NUMBER(5,4) DEFAULT 0 NOT NULL,
  reporter_evidence     VARCHAR2(2000),
  has_product           CHAR(1)     DEFAULT 'N' NOT NULL,
  product_confidence    NUMBER(5,4) DEFAULT 0 NOT NULL,
  product_evidence      VARCHAR2(2000),
  has_event             CHAR(1)     DEFAULT 'N' NOT NULL,
  event_confidence      NUMBER(5,4) DEFAULT 0 NOT NULL,
  event_evidence        VARCHAR2(2000),
  elements_present      NUMBER(2)   DEFAULT 0 NOT NULL,
  missing_elements_json VARCHAR2(500),
  CONSTRAINT fk_validity_classification FOREIGN KEY (classification_id)
    REFERENCES classification (id) ON DELETE CASCADE,
  CONSTRAINT ck_validity_patient  CHECK (has_patient  IN ('Y','N')),
  CONSTRAINT ck_validity_reporter CHECK (has_reporter IN ('Y','N')),
  CONSTRAINT ck_validity_product  CHECK (has_product  IN ('Y','N')),
  CONSTRAINT ck_validity_event    CHECK (has_event    IN ('Y','N'))
);


-- -------------------------------------------------------------------------------------
-- 11. CASE_RECORD — one extracted case. case_index exists from day one (E32), which is why
--     the literature bonus needs no schema change: one document can hold N cases.
-- -------------------------------------------------------------------------------------
CREATE TABLE case_record (
  id               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id       NUMBER(19),
  document_id      NUMBER(19),
  case_index       NUMBER(6)    DEFAULT 0 NOT NULL,
  case_type        VARCHAR2(20) NOT NULL,
  patient_descriptor VARCHAR2(500),
  narrative        CLOB,
  -- E35: seriousness is the six regulatory criteria as independent booleans in JSON, not a
  -- severity slider and not free text.
  is_serious       CHAR(1)      DEFAULT 'N' NOT NULL,
  seriousness_json VARCHAR2(2000),
  confidence       NUMBER(5,4)  DEFAULT 0 NOT NULL,
  page_from        NUMBER(6),
  page_to          NUMBER(6),
  ai_call_id       NUMBER(19),
  created_at       TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_case_message FOREIGN KEY (message_id)
    REFERENCES inbox_message (id) ON DELETE CASCADE,
  CONSTRAINT fk_case_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_case_type CHECK (case_type IN ('ICSR','PQC','MI')),
  CONSTRAINT ck_case_serious CHECK (is_serious IN ('Y','N'))
);


-- -------------------------------------------------------------------------------------
-- 12. EXTRACTED_FIELD — one row per fact. Both the model's raw confidence and the final
--     adjusted value are stored, with the reason, so the write-up can show exactly how much
--     of a score is model self-report and how much is system verification (§11.5).
-- -------------------------------------------------------------------------------------
CREATE TABLE extracted_field (
  id                    NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id               NUMBER(19)   NOT NULL,
  field_group           VARCHAR2(40) NOT NULL,
  field_path            VARCHAR2(200) NOT NULL,
  field_index           NUMBER(6)    DEFAULT 0 NOT NULL,   -- E31: arrays of products/reactions
  value_text            VARCHAR2(4000),
  value_json            CLOB,                              -- E28/E29/E30 typed values
  value_en              VARCHAR2(4000),                    -- E16 translation, never evidentiary
  unit                  VARCHAR2(40),
  raw_text              VARCHAR2(2000),                    -- E29: the source string is never destroyed
  status                VARCHAR2(20) DEFAULT 'NOT_STATED' NOT NULL,
  confidence            NUMBER(5,4)  DEFAULT 0 NOT NULL,
  confidence_pre_adjust NUMBER(5,4),
  adjust_reason         VARCHAR2(500),
  decided_by            VARCHAR2(20) DEFAULT 'AI' NOT NULL,
  decided_by_user       VARCHAR2(200),
  superseded_by         NUMBER(19),                        -- E40 append-only override
  created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_field_case FOREIGN KEY (case_id)
    REFERENCES case_record (id) ON DELETE CASCADE,
  CONSTRAINT fk_field_superseded FOREIGN KEY (superseded_by)
    REFERENCES extracted_field (id),
  -- NOT_STATED is a first-class answer, never an error state (CLAUDE.md constraint 4).
  CONSTRAINT ck_field_status CHECK (status IN ('STATED','NOT_STATED','UNCERTAIN','CONFLICT')),
  CONSTRAINT ck_field_conf CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT ck_field_decided CHECK (decided_by IN ('AI','REVIEWER','RULE'))
);


-- -------------------------------------------------------------------------------------
-- 13. FIELD_EVIDENCE — the differentiator (E27). VERIFIED is written by pipeline/verify.py
--     after it proves the quote occurs in the page text. A model-asserted citation that
--     cannot be proved lands here as verified='N' and caps the field's confidence at 0.40.
-- -------------------------------------------------------------------------------------
CREATE TABLE field_evidence (
  id            NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_id      NUMBER(19)   NOT NULL,
  source_type   VARCHAR2(20) NOT NULL,
  document_id   NUMBER(19),
  page_no       NUMBER(6),
  quote         VARCHAR2(4000),
  -- Offsets are REWRITTEN by the verifier to the real position found in the source; the
  -- model's own numbers are never kept.
  char_start    NUMBER(10),
  char_end      NUMBER(10),
  bbox          VARCHAR2(200),
  verified      CHAR(1)      DEFAULT 'N' NOT NULL,
  verify_method VARCHAR2(20) DEFAULT 'FAILED' NOT NULL,
  match_score   NUMBER(6,2),
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_evidence_field FOREIGN KEY (field_id)
    REFERENCES extracted_field (id) ON DELETE CASCADE,
  CONSTRAINT fk_evidence_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_evidence_source CHECK (source_type IN ('EMAIL_BODY','PDF_PAGE','TABLE','IMAGE')),
  CONSTRAINT ck_evidence_verified CHECK (verified IN ('Y','N')),
  CONSTRAINT ck_evidence_method CHECK (verify_method IN ('EXACT','FUZZY','FAILED'))
);

COMMENT ON TABLE field_evidence IS
  'Machine-verified provenance. verified=Y means code found the quote in the source, not that the model claimed it.';


-- -------------------------------------------------------------------------------------
-- 14. JOB — the durable work queue. Dequeued with FOR UPDATE SKIP LOCKED by PKG_JOB_QUEUE,
--     so the pipeline is asynchronous and restart-safe (R18, E37, E38).
-- -------------------------------------------------------------------------------------
CREATE TABLE job (
  id            NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type      VARCHAR2(40) NOT NULL,
  subject_type  VARCHAR2(20) NOT NULL,
  subject_id    NUMBER(19)   NOT NULL,
  state         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  priority      NUMBER(3)    DEFAULT 5 NOT NULL,
  attempts      NUMBER(4)    DEFAULT 0 NOT NULL,
  max_attempts  NUMBER(4)    DEFAULT 3 NOT NULL,
  available_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  locked_by     VARCHAR2(100),
  locked_at     TIMESTAMP(6) WITH TIME ZONE,
  last_error    VARCHAR2(4000),
  payload_json  VARCHAR2(4000),
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_job_type CHECK (job_type IN (
    'PARSE_DOCUMENT','CLASSIFY_MESSAGE','EXTRACT_CASE','FINALISE_MESSAGE','SCREEN_ARTICLE')),
  CONSTRAINT ck_job_state CHECK (state IN ('PENDING','RUNNING','DONE','FAILED','DEAD')),
  CONSTRAINT ck_job_subject CHECK (subject_type IN ('MESSAGE','DOCUMENT','BATCH'))
);


-- -------------------------------------------------------------------------------------
-- 15. AI_CALL_LOG — R15. The exact request and response behind every AI decision, with the
--     prompt version, token counts, measured dollar cost and latency. GET /api/ai-calls/{id}
--     renders this, so "why did the system say this?" is answerable in two clicks.
--     The API key never appears here (CLAUDE.md constraint 3).
-- -------------------------------------------------------------------------------------
CREATE TABLE ai_call_log (
  id                NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id            NUMBER(19),
  correlation_id    VARCHAR2(64),
  purpose           VARCHAR2(60) NOT NULL,
  model             VARCHAR2(100) NOT NULL,
  prompt_version    VARCHAR2(40),
  request_json      CLOB,
  response_json     CLOB,
  prompt_tokens     NUMBER(10) DEFAULT 0 NOT NULL,
  completion_tokens NUMBER(10) DEFAULT 0 NOT NULL,
  cached_tokens     NUMBER(10) DEFAULT 0 NOT NULL,
  cache_write_tokens NUMBER(10) DEFAULT 0 NOT NULL,
  cost_usd          NUMBER(12,8) DEFAULT 0 NOT NULL,
  latency_ms        NUMBER(10),
  http_status       NUMBER(5),
  retries           NUMBER(4)  DEFAULT 0 NOT NULL,
  repaired          CHAR(1)    DEFAULT 'N' NOT NULL,
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_ai_call_repaired CHECK (repaired IN ('Y','N'))
);


-- -------------------------------------------------------------------------------------
-- 16. AUDIT_EVENT — append-only. Written through PKG_AUDIT with PRAGMA
--     AUTONOMOUS_TRANSACTION so the audit row survives a rolled-back business transaction.
-- -------------------------------------------------------------------------------------
CREATE TABLE audit_event (
  id             NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correlation_id VARCHAR2(64),
  actor          VARCHAR2(200) NOT NULL,
  actor_type     VARCHAR2(20)  NOT NULL,
  action         VARCHAR2(60)  NOT NULL,
  entity_type    VARCHAR2(40)  NOT NULL,
  entity_id      NUMBER(19),
  message_id     NUMBER(19),
  before_json    CLOB,
  after_json     CLOB,
  occurred_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_audit_actor_type CHECK (actor_type IN ('SYSTEM','REVIEWER'))
);


-- -------------------------------------------------------------------------------------
-- 17. REVIEW_DECISION — the human's verdict on a message (R9, E40).
-- -------------------------------------------------------------------------------------
CREATE TABLE review_decision (
  id                    NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id            NUMBER(19)   NOT NULL,
  reviewer              VARCHAR2(200) NOT NULL,
  decision              VARCHAR2(20) NOT NULL,
  final_categories_json VARCHAR2(500),
  notes                 VARCHAR2(4000),
  decided_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_review_message FOREIGN KEY (message_id)
    REFERENCES inbox_message (id) ON DELETE CASCADE,
  CONSTRAINT ck_review_decision CHECK (decision IN ('ACCEPT','OVERRIDE','REJECT'))
);


-- -------------------------------------------------------------------------------------
-- 18. PROCESSING_METRIC — per-stage timings behind the R17 batch report.
-- -------------------------------------------------------------------------------------
CREATE TABLE processing_metric (
  id           NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_type VARCHAR2(20) NOT NULL,
  subject_id   NUMBER(19)   NOT NULL,
  stage        VARCHAR2(40) NOT NULL,
  duration_ms  NUMBER(10)   NOT NULL,
  succeeded    CHAR(1)      DEFAULT 'Y' NOT NULL,
  created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_metric_succeeded CHECK (succeeded IN ('Y','N'))
);


-- -------------------------------------------------------------------------------------
-- 19–20. Literature screening (bonus, §4 of the brief). CASE_RECORD already carries
--        case_index, so these two tables are the entire persistence cost of the bonus.
-- -------------------------------------------------------------------------------------
CREATE TABLE literature_batch (
  id            NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_name    VARCHAR2(200),
  uploaded_by   VARCHAR2(200),
  file_count    NUMBER(6)    DEFAULT 0 NOT NULL,
  status        VARCHAR2(30) DEFAULT 'RECEIVED' NOT NULL,
  created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT ck_lit_batch_status CHECK (status IN ('RECEIVED','SCREENING','DONE','FAILED'))
);

CREATE TABLE literature_item (
  id                NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id          NUMBER(19)   NOT NULL,
  document_id       NUMBER(19),
  filename          VARCHAR2(500),
  is_case_report    CHAR(1)      DEFAULT 'N' NOT NULL,
  confidence        NUMBER(5,4)  DEFAULT 0 NOT NULL,
  relevance_reason  VARCHAR2(2000),
  case_count        NUMBER(6)    DEFAULT 0 NOT NULL,
  excluded_sections VARCHAR2(1000),
  status            VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  error_text        VARCHAR2(2000),
  ai_call_id        NUMBER(19),
  created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_lit_item_batch FOREIGN KEY (batch_id)
    REFERENCES literature_batch (id) ON DELETE CASCADE,
  CONSTRAINT fk_lit_item_document FOREIGN KEY (document_id)
    REFERENCES document (id) ON DELETE CASCADE,
  CONSTRAINT ck_lit_item_case_report CHECK (is_case_report IN ('Y','N')),
  CONSTRAINT ck_lit_item_status CHECK (status IN ('PENDING','SCREENING','DONE','FAILED'))
);
